### ISSUE TITLE
Need A Method To Shut Down Server Through Code

### ISSUE THREAD

**Issue by jayitinc** [jayitinc/song-bot#1]
If anyone is good with Meteor and/or Electron and knows how to **programmaticaly shut down the meteor server** let me know or **create a pull request**.

**Comment by AtecStudios** [comment]
You can close the server and intern the app using `process.exit()`.

**Comment by jayitinc** [comment]
@AtecStudios thanks, I'll try it when I get home.

**Comment by jayitinc** [comment]
> You can close the server and intern the app using `process.exit()`. 

This solution works. To anyone using this solution use the `--once` tag when launching Meteor or else the server will restart itself **(atleast on dev, I don't know about production)**.
